volumes:
  home:

services:
  openclaw:
    build: .
    restart: always
    expose:
      - 80
      - 8787
      - 18789
      - 51121
    volumes:
      - home:/home/node
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/tmux-1000:/tmp/tmux-1000
